/** @format */

import { StyleSheet } from "react-native";
import { COLOR } from "../common/color";
// import { getScaledHeight, windowWidth } from "./dimension";

const marginTopElement = 20;
const minScape = 5;

export const verticalPaddingElement = 10;
export const opacityActive = 0.6;
export const BASE_STYLES = StyleSheet.create({
  // CONTAINER, CONTENT STYLES
  flex0d1: { flex: 0.1 },
  flex0d2: { flex: 0.2 },
  flex0d4: { flex: 0.4 },
  flex1: { flex: 1 },
  flex2: { flex: 2 },
  zIndex1: { zIndex: 1 },
  maxHeight100: { maxHeight: "100%" },
  flexGrow1: { flexGrow: 1 },
  flexDirectColumn: { flexDirection: "column" },
  flexDirectRow: { flexDirection: "row" },
  flexWrap: { flexWrap: "wrap" },
  flexRow: { flex: 1, flexDirection: "row" },
  flexRowWrap: { flex: 1, flexDirection: "row", flexWrap: "wrap" },
  justifyCenter: { justifyContent: "center" },
  justifyFlexEnd: { justifyContent: "flex-end" },
  justifyBetween: { justifyContent: "space-between" },
  alignCenter: { alignItems: "center" },
  alignLeft: { alignItems: "flex-start" },
  alignEnd: { alignItems: "flex-end" },
  alignSelfCenter: { alignSelf: "center" },
  alignSelfEnd: { alignSelf: "flex-end" },
  textCenter: { textAlign: "center" },
  textRight: { textAlign: "right" },
  //POSITION
  positionAbsolute: { position: "absolute" },
  //BOTTOM
  bottom0: { bottom: 0 },
  bottom5: { bottom: 5 },
  bottom20: { bottom: 20 },
  bottom30: { bottom: 30 },
  hitSlopIcon: { top: 20, bottom: 20, left: 30, right: 30 },
  // LEFT
  left42Percent: { left: "42%" },
  left70: { left: 70 },
  //WIDTH COMMON
  //   width90_device: { width: windowWidth * 0.9 },
  width100Percent: { width: "100%" },
  width90Percent: { width: "90%" },
  width80Percent: { width: "80%" },
  width50Percent: { width: "50%" },
  width65Percent: { width: "65%" },
  width60Percent: { width: "60%" },
  width35Percent: { width: "35%" },
  width13Percent: { width: "13%" },
  width40: { width: 40 },
  width28: { width: 28 },
  width200: { width: 200 },
  width100: { width: 100 },
  //HEIGHT COMMON
  height100Percent: { height: "100%" },
  height330: { height: 330 },
  height250: { height: 250 },
  height100: { height: 100 },
  height90: { height: 90 },
  height40: { height: 40 },
  height0: { height: 0 },
  width90WithPadding: { width: "90%", paddingHorizontal: "3%" },
  //MARGIN PROPERTIES COMMON
  marginVertical77: { marginVertical: 77 },
  marginVertical20: { marginVertical: 20 },
  marginVertical10: { marginVertical: 10 },
  marginHorizontal100: { marginHorizontal: 100 },
  marginHorizontal20: { marginHorizontal: 20 },
  marginHorizontal10: { marginHorizontal: 10 },
  marginRight20: { marginRight: 20 },
  marginTop30: { marginTop: 30 },
  marginTop15: { marginTop: 15 },
  marginTop20: { marginTop: 20 },
  marginTop10: { marginTop: 10 },
  marginTop5: { marginTop: 5 },
  marginRight10: { marginRight: 10 },
  marginRight5: { marginRight: 5 },
  marginBottom30: { marginBottom: 30 },
  marginBottom20: { marginBottom: 20 },
  marginBottom15: { marginBottom: 15 },
  marginBottom10: { marginBottom: 10 },
  marginBottom5: { marginBottom: 5 },
  marginLeft40: { marginLeft: 40 },
  marginLeft20: { marginLeft: 20 },
  marginLeft16: { marginLeft: 16 },
  marginLeft10: { marginLeft: 10 },
  marginLeft5: { marginLeft: 5 },
  marginLeft3: { marginLeft: 3 },
  //PADDING PROPERTIES COMMON
  paddingVertical10: { paddingVertical: verticalPaddingElement },
  paddingHorizontal12: { paddingHorizontal: 12 },
  paddingHorizontal20: { paddingHorizontal: 20 },
  paddingHorizontal10: { paddingHorizontal: 10 },
  paddingElement: { paddingVertical: verticalPaddingElement, paddingRight: 10 },
  padding5: { padding: 5 },
  padding10: { padding: 10 },
  paddingTop100: { paddingTop: 100 },
  paddingTop20: { paddingTop: 20 },
  paddingTop15: { paddingTop: 15 },
  paddingTop10: { paddingTop: 10 },
  paddingBottom20: { paddingBottom: marginTopElement },
  paddingBottom15: { paddingBottom: 15 },
  paddingBottom10: { paddingBottom: 10 },
  paddingRight40: { paddingRight: 40 },
  paddingRight10: { paddingRight: 10 },
  paddingLeft15: { paddingLeft: 15 },
  paddingLeft10: { paddingLeft: 10 },
  paddingLeft5: { paddingLeft: minScape },
  paddingTop5: { paddingTop: minScape },
  paddingBottom5: { paddingBottom: minScape },
  //PLACEHOLDER COMMON STYLES
  errorInfo: { marginTop: 15, fontSize: 14, color: COLOR.DEFAULT_RED },
  errorColor: { color: COLOR.DEFAULT_RED },
  //   textInputStyle: { height: getScaledHeight(50) },
  textButtonCenter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  //BORDER COMMON STYLES
  borderCircle: { width: 36, height: 36, borderRadius: 18, borderWidth: 1 },
  borderBottom: { borderBottomWidth: 1 },
  noBorderBottom: { borderBottomWidth: 0 },
  borderRadius5: { borderRadius: 5 },
  borderRadius12: { borderRadius: 12 },
  borderLine: { height: 1 },
  borderTextBox: { borderRadius: 12, borderWidth: 1 },
  borderRadiusTop: { borderTopLeftRadius: 16, borderTopRightRadius: 16 },
  //Line height
  lineHeight15: { lineHeight: 15 },
  lineHeight16: { lineHeight: 16 },
  // ELEMENT COMMON STYLES:
  buttonCenter: {
    alignItems: "center",
    margin: 0,
    // height: (windowWidth * 0.9 * 41) / 335,
    height: 45,
    borderRadius: 12,
    borderColor: COLOR.transparent,
  },
  topBorder: { borderTopWidth: 0.4 },
  disableStyle: { backgroundColor: "#00000000", color: "#777" },
  labelCenter: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  switchContainer: {
    borderRadius: 40,
    height: 26,
    width: 40,
    justifyContent: "center",
  },
  switchTrack: {
    margin: 4,
    borderRadius: 50,
    width: 20,
    height: 20,
    position: "absolute",
  },
  leftPaddingTextInput: { paddingLeft: verticalPaddingElement + minScape },
  jobDetail: { marginTop: 20, marginBottom: 20, width: "90%" },
  //LIST JOB
  fontWeightBold: { fontWeight: "bold" },
  //   maxWidth30Percent: { maxWidth: windowWidth * 0.3 },
  fontSize8: { fontSize: 8 },
  fontSize10: { fontSize: 10 },
  listCardItem: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 5,
  },
  positionOnTop: { position: "absolute", right: 0, top: 0 },
  positionOnRight: { position: "absolute", right: 0 },
  tabHeader: { marginTop: 20, marginRight: 30, paddingBottom: 8 },
  detailItem: {
    flex: 1,
    flexDirection: "row",
    paddingTop: 10,
    paddingBottom: 10,
  },
  stickSpace: { width: 1, height: 10, marginLeft: 15, marginRight: 15 },
  itemBorderBottom: { borderBottomWidth: 0.8 },
  itemBorderTop: { borderTopWidth: 0.8 },
  // LIST ITEM
  overFlowHidden: { overflow: "hidden" },
  shadow: {
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.23,
    shadowRadius: 2.62,
    elevation: 4,
  },
  listItem: { borderWidth: 1, padding: 10, borderRadius: 12 },
  viewWithBorder: { borderWidth: 1, borderRadius: 12 },
  //ICON-LIST STYLES
  iconUrgent: {
    backgroundColor: COLOR.GREEN,
    borderRadius: 50,
    width: 10,
    height: 10,
    marginRight: 10,
  },
  iconUrgentRed: { backgroundColor: COLOR.DEFAULT_RED },
  icon: {
    width: 42,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    borderWidth: 1,
    opacity: 0.9,
  },
  iconActive: { borderWidth: 1.4 },
  iconViewAll: { backgroundColor: COLOR.GREY_LIGHT, borderColor: COLOR.GREY },
  // WORKER MANAGEMENT
  workerItemStyle: {
    width: "100%",
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  animateStyle: { flex: 1, height: "100%", position: "absolute", width: 90 },
  swipeStyle: {
    marginLeft: 10,
    justifyContent: "center",
    flex: 1,
    alignItems: "center",
  },
  cardStyle: {
    borderWidth: 1,
    borderRadius: 12,
    height: 97,
    paddingHorizontal: 20,
  },
  workerStyle: { borderWidth: 1, borderRadius: 12, paddingHorizontal: 20 },
  deleteButton: {
    marginLeft: 10,
    justifyContent: "center",
    flex: 1,
    alignItems: "center",
    backgroundColor: COLOR.DEFAULT_RED,
    borderTopRightRadius: 14,
    borderBottomRightRadius: 14,
    zIndex: 0,
    left: 50,
  },
  enableButton: {
    backgroundColor: COLOR.BLUE,
    marginLeft: 10,
    justifyContent: "center",
    flex: 1,
    alignItems: "center",
    borderTopRightRadius: 14,
    borderBottomRightRadius: 14,
    zIndex: 1,
    left: -20,
  },
  disableButton: {
    backgroundColor: COLOR.GREY,
    marginLeft: 10,
    justifyContent: "center",
    flex: 1,
    alignItems: "center",
    borderTopRightRadius: 14,
    borderBottomRightRadius: 14,
    zIndex: 1,
    left: -20,
  },
  buttonTextStyle: { marginTop: 5, color: COLOR.WHITE },
  // Image
  resizeModeCover: { resizeMode: "cover" },
  messageImageStyle: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    resizeMode: "cover",
  },
  tagService: { margin: 5, marginLeft: 0, borderWidth: 1, borderRadius: 20 },
});
